# Generated by Django 4.2.7 on 2025-09-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'dietitian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='user_management.userprofile'),
        ),
    ]
