from django.core.management.base import BaseCommand
from diet_planner.models import Food


class Command(BaseCommand):
    help = 'Populate the food database with sample Ayurvedic foods'

    def handle(self, *args, **options):
        foods_data = [
            # Grains
            {
                'name': 'Basmati Rice',
                'category': 'grains',
                'subcategory': 'white_rice',
                'calories': 130,
                'protein': 2.7,
                'carbohydrates': 28.0,
                'fat': 0.3,
                'fiber': 0.4,
                'primary_taste': 'sweet',
                'energy': 'cooling',
                'vata_effect': 'pacifies',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Brown Rice',
                'category': 'grains',
                'subcategory': 'brown_rice',
                'calories': 111,
                'protein': 2.6,
                'carbohydrates': 23.0,
                'fat': 0.9,
                'fiber': 1.8,
                'primary_taste': 'sweet',
                'energy': 'cooling',
                'vata_effect': 'pacifies',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Quinoa',
                'category': 'grains',
                'subcategory': 'pseudo_grains',
                'calories': 120,
                'protein': 4.4,
                'carbohydrates': 22.0,
                'fat': 1.9,
                'fiber': 2.8,
                'primary_taste': 'sweet',
                'secondary_taste': 'astringent',
                'energy': 'cooling',
                'vata_effect': 'pacifies',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'neutral',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            
            # Vegetables
            {
                'name': 'Spinach',
                'category': 'vegetables',
                'subcategory': 'leafy_greens',
                'calories': 23,
                'protein': 2.9,
                'carbohydrates': 3.6,
                'fat': 0.4,
                'fiber': 2.2,
                'primary_taste': 'bitter',
                'secondary_taste': 'astringent',
                'energy': 'cooling',
                'vata_effect': 'aggravates',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'pacifies',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Kale',
                'category': 'vegetables',
                'subcategory': 'leafy_greens',
                'calories': 49,
                'protein': 4.3,
                'carbohydrates': 8.8,
                'fat': 0.9,
                'fiber': 3.6,
                'primary_taste': 'bitter',
                'secondary_taste': 'astringent',
                'energy': 'cooling',
                'vata_effect': 'aggravates',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'pacifies',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Sweet Potato',
                'category': 'vegetables',
                'subcategory': 'root_vegetables',
                'calories': 86,
                'protein': 1.6,
                'carbohydrates': 20.1,
                'fat': 0.1,
                'fiber': 3.0,
                'primary_taste': 'sweet',
                'energy': 'heating',
                'vata_effect': 'pacifies',
                'pitta_effect': 'aggravates',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Carrot',
                'category': 'vegetables',
                'subcategory': 'root_vegetables',
                'calories': 41,
                'protein': 0.9,
                'carbohydrates': 9.6,
                'fat': 0.2,
                'fiber': 2.8,
                'primary_taste': 'sweet',
                'energy': 'cooling',
                'vata_effect': 'pacifies',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'neutral',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            
            # Fruits
            {
                'name': 'Apple',
                'category': 'fruits',
                'subcategory': 'pome_fruits',
                'calories': 52,
                'protein': 0.3,
                'carbohydrates': 13.8,
                'fat': 0.2,
                'fiber': 2.4,
                'primary_taste': 'sweet',
                'secondary_taste': 'astringent',
                'energy': 'cooling',
                'vata_effect': 'pacifies',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Banana',
                'category': 'fruits',
                'subcategory': 'tropical_fruits',
                'calories': 89,
                'protein': 1.1,
                'carbohydrates': 22.8,
                'fat': 0.3,
                'fiber': 2.6,
                'primary_taste': 'sweet',
                'energy': 'cooling',
                'vata_effect': 'pacifies',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Orange',
                'category': 'fruits',
                'subcategory': 'citrus_fruits',
                'calories': 47,
                'protein': 0.9,
                'carbohydrates': 11.8,
                'fat': 0.1,
                'fiber': 2.4,
                'primary_taste': 'sour',
                'secondary_taste': 'sweet',
                'energy': 'cooling',
                'vata_effect': 'aggravates',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'neutral',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            
            # Proteins
            {
                'name': 'Lentils (Red)',
                'category': 'proteins',
                'subcategory': 'legumes',
                'calories': 116,
                'protein': 9.0,
                'carbohydrates': 20.1,
                'fat': 0.4,
                'fiber': 7.9,
                'primary_taste': 'sweet',
                'secondary_taste': 'astringent',
                'energy': 'heating',
                'vata_effect': 'pacifies',
                'pitta_effect': 'aggravates',
                'kapha_effect': 'neutral',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Chickpeas',
                'category': 'proteins',
                'subcategory': 'legumes',
                'calories': 164,
                'protein': 8.9,
                'carbohydrates': 27.4,
                'fat': 2.6,
                'fiber': 7.6,
                'primary_taste': 'sweet',
                'secondary_taste': 'astringent',
                'energy': 'heating',
                'vata_effect': 'pacifies',
                'pitta_effect': 'aggravates',
                'kapha_effect': 'neutral',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Almonds',
                'category': 'proteins',
                'subcategory': 'nuts',
                'calories': 579,
                'protein': 21.2,
                'carbohydrates': 21.6,
                'fat': 49.9,
                'fiber': 12.5,
                'primary_taste': 'sweet',
                'energy': 'heating',
                'vata_effect': 'pacifies',
                'pitta_effect': 'aggravates',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
                'contains_nuts': True,
            },
            
            # Dairy
            {
                'name': 'Ghee',
                'category': 'dairy',
                'subcategory': 'fats',
                'calories': 900,
                'protein': 0.0,
                'carbohydrates': 0.0,
                'fat': 100.0,
                'fiber': 0.0,
                'primary_taste': 'sweet',
                'energy': 'heating',
                'vata_effect': 'pacifies',
                'pitta_effect': 'aggravates',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': False,
                'is_gluten_free': True,
                'is_dairy_free': False,
            },
            {
                'name': 'Yogurt',
                'category': 'dairy',
                'subcategory': 'fermented',
                'calories': 59,
                'protein': 10.0,
                'carbohydrates': 3.6,
                'fat': 0.4,
                'fiber': 0.0,
                'primary_taste': 'sour',
                'secondary_taste': 'sweet',
                'energy': 'cooling',
                'vata_effect': 'aggravates',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'aggravates',
                'is_vegetarian': True,
                'is_vegan': False,
                'is_gluten_free': True,
                'is_dairy_free': False,
            },
            
            # Spices
            {
                'name': 'Turmeric',
                'category': 'spices',
                'subcategory': 'roots',
                'calories': 354,
                'protein': 7.8,
                'carbohydrates': 64.9,
                'fat': 9.9,
                'fiber': 21.1,
                'primary_taste': 'bitter',
                'secondary_taste': 'pungent',
                'energy': 'heating',
                'vata_effect': 'pacifies',
                'pitta_effect': 'pacifies',
                'kapha_effect': 'pacifies',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
            {
                'name': 'Ginger',
                'category': 'spices',
                'subcategory': 'roots',
                'calories': 80,
                'protein': 1.8,
                'carbohydrates': 17.8,
                'fat': 0.8,
                'fiber': 2.0,
                'primary_taste': 'pungent',
                'secondary_taste': 'sweet',
                'energy': 'heating',
                'vata_effect': 'pacifies',
                'pitta_effect': 'aggravates',
                'kapha_effect': 'pacifies',
                'is_vegetarian': True,
                'is_vegan': True,
                'is_gluten_free': True,
                'is_dairy_free': True,
            },
        ]
        
        created_count = 0
        for food_data in foods_data:
            food, created = Food.objects.get_or_create(
                name=food_data['name'],
                defaults=food_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'Created food: {food.name}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'Food already exists: {food.name}')
                )
        
        self.stdout.write(
            self.style.SUCCESS(f'Successfully created {created_count} new foods in the database!')
        )


