# Generated by Django 4.2.7 on 2025-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
