# Generated by Django 4.2.7 on 2025-09-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='secondary_taste',
            field=models.CharField(blank=True, choices=[('sweet', 'Sweet'), ('sour', 'Sour'), ('salty', 'Salty'), ('pungent', 'Pungent'), ('bitter', 'Bitter'), ('astringent', 'Astringent')], max_length=20, null=True),
        ),
    ]
