# Generated by Django 4.2.7 on 2025-09-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0002_alter_food_secondary_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
