# Generated by Django 4.2.7 on 2025-09-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('diet_planner', '0004_alter_patient_activity_level_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_patient', to='user_management.userprofile'),
        ),
    ]
