# Generated by Django 4.2.7 on 2025-09-20 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains'), ('proteins', 'Proteins'), ('dairy', 'Dairy'), ('spices', 'Spices'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('desserts', 'Desserts'), ('other', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_database/')),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbohydrates', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('fiber', models.FloatField(default=0.0)),
                ('sugar', models.FloatField(default=0.0)),
                ('rasa', models.CharField(blank=True, max_length=50)),
                ('virya', models.CharField(blank=True, max_length=50)),
                ('vipaka', models.CharField(blank=True, max_length=50)),
                ('guna', models.CharField(blank=True, max_length=100)),
                ('vata_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral'), ('moderate', 'Moderate'), ('avoid', 'Avoid')], default='neutral', max_length=20)),
                ('pitta_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral'), ('moderate', 'Moderate'), ('avoid', 'Avoid')], default='neutral', max_length=20)),
                ('kapha_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral'), ('moderate', 'Moderate'), ('avoid', 'Avoid')], default='neutral', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ayurvedic_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('camera', 'Camera Scan'), ('upload', 'File Upload')], max_length=20)),
                ('image', models.ImageField(upload_to='food_scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detected_food', models.CharField(blank=True, max_length=200)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbohydrates', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('fiber', models.FloatField(default=0.0)),
                ('sugar', models.FloatField(default=0.0)),
                ('rasa', models.CharField(blank=True, max_length=50)),
                ('virya', models.CharField(blank=True, max_length=50)),
                ('vipaka', models.CharField(blank=True, max_length=50)),
                ('guna', models.CharField(blank=True, max_length=100)),
                ('vata_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral'), ('moderate', 'Moderate'), ('avoid', 'Avoid')], default='neutral', max_length=20)),
                ('pitta_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral'), ('moderate', 'Moderate'), ('avoid', 'Avoid')], default='neutral', max_length=20)),
                ('kapha_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral'), ('moderate', 'Moderate'), ('avoid', 'Avoid')], default='neutral', max_length=20)),
                ('ayurvedic_description', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
