# Generated by Django 4.2.7 on 2025-09-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddatabase',
            name='meal_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fooddatabase',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fooddatabase',
            name='primary_taste',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fooddatabase',
            name='energy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fooddatabase',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooddatabase',
            name='avoidances',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='fooddatabase',
            name='ayurvedic_description',
        ),
        migrations.RemoveField(
            model_name='fooddatabase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fooddatabase',
            name='rasa',
        ),
        migrations.RemoveField(
            model_name='fooddatabase',
            name='virya',
        ),
        migrations.AlterField(
            model_name='fooddatabase',
            name='category',
            field=models.CharField(blank=True, choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains', 'Grains'), ('proteins', 'Proteins'), ('dairy', 'Dairy'), ('spices', 'Spices'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('desserts', 'Desserts'), ('other', 'Other')], max_length=50),
        ),
    ]
